### ISSUE TITLE
Jhipster 3.4.0 not updated to support google maps

### ISSUE THREAD

**Issue by Ljilja7** [moifort/generator-jhipster-google-maps#6]
Hi,

I found the same error with 3.4.0 as one already reported for 3.1.0. When we can expect this support?

Thanks

(1/1) What is your google API key? 
Composing JHipster configuration with module google-maps
Reading the JHipster project configuration for your module
events.js:141
throw er; // Unhandled 'error' event
^

TypeError: jhipsterFunc.addAngularJsConfig is not a function
at module.exports.yeoman.generators.Base.extend.writing (/usr/lib/node_modules/generator-jhipster-google-maps/generators/app/index.js:73:22)
at /usr/lib/node_modules/generator-jhipster-google-maps/node_modules/yeoman-generator/lib/base.js:430:16
at processImmediate as _immediateCallback

**Comment by ecoecoecoecoecoecoecoecoecoecoecoeco** [comment]
This error still persist in generator-jhipster@3.10.0, Any suggest to resolve it?

**Comment by pascalgrimaud** [comment]
@Carloospm : probably because this module hasn't been updated for a long time
So PR are welcome to update it !

**Comment by cartsofware** [comment]
+1

**Comment by finxster** [comment]
+1

**Comment by finxster** [comment]
@pascalgrimaud https://github.com/moifort/generator-jhipster-google-maps/pull/7 :)

**Comment by pascalgrimaud** [comment]
Wow thanks for your contribution @finxster
Give me time to review and merge it

**Comment by pascalgrimaud** [comment]
Should be fixed by https://github.com/moifort/generator-jhipster-google-maps/pull/7
